#!/usr/bin/bash


function log() {
    echo "$(date)  $1" >> /var/log/bootstrap_stages.log
    echo "$(date) ********** $1 **********"
}

target_user=TARGET_USER
log "starting bootstrap script. target_user is $target_user"

if [ -f /usr/lib/systemd/system/bootstrap.service ]; then
    log 'removing bootstrap.service'
    systemctl disable bootstrap.service
    rm /usr/lib/systemd/system/bootstrap.service
fi


function on_error() {
    log 'fatal error $1' 
    exit 1
}


if [ ! `uname -m` == "armv7l" ]; then on_error "This script must be run on the rpi"; fi
if [ ! `id -u` == "0" ]; then on_error "Run this script as root"; fi

log 'handling keys...' 
pacman-key --init || on_error "initing keys"
pacman-key --populate || on_error "populating keys"
pacman -Sy archlinuxarm-keyring --noconfirm

log 'updating base system...'
pacman -Su git --noconfirm
pacman -R --noconfirm linux-firmware
pacman -R --noconfirm `pacman -Qsq linux-firmware-`
pacman -S --noconfirm linux-firmware-broadcom


log 'installing main packages...' 
pacman -S --needed --noconfirm `cat /root/packages_catador_main`

log 'installing dev packages...'
pacman -S --needed --noconfirm `cat /root/packages_catador_dev`

log 'building ncnn...'
sudo -u $target_user bash -c "cd /home/${target_user} && \
           git clone https://github.com/Tencent/ncnn.git && \
           cd ncnn && mkdir build && \
           cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchains/pi3.toolchain.cmake \
                    -DCMAKE_INSTALL_PREFIX=/usr/local && make -j2"
log 'installing ncnn...'
make -C /home/${target_user}/ncnn/build install 

log 'installing extra pacman packages...'
packages=/root/*.pkg.tar.xz

#FIXME does this work for more than one package?
if [ ! "$packages" == '*.pkg.tar.xz' ]; then
    pacman -U --noconfirm $packages || on_error "on installing $packages"
    log "installed $packages"
fi

log 'building nvim-packer-git...'
sudo -u $target_user bash -c "cd /home/${target_user} && \
                       git clone https://aur.archlinux.org/nvim-packer-git.git && \
                       cd nvim-packer-git && \
                       makepkg"

log 'installing nvim-packer-git...'
pacman --noconfirm -U /home/${target_user}/nvim-packer-git/nvim-packer-git*.pkg.tar.xz || \
    on_error "on creating or installing nvim-packer-git"
rm /home/${target_user}/nvim-packer-git -rf || on_error

log 'ending with success.'
